rh-event-flow/eventflow

- manager/src/main/java/io/streamzi/openshift/API.java
- manager/src/main/java/io/streamzi/openshift/ProcessorFlowDeployer.java
- operations/nodejs/filter-events/main.js
- operations/nodejs/filter-events/streamzi.yml
Restructured the deployment so that one flow gets deployed into multiple apps. 
Probably could be refactored a bit better but suggest doing this as part of moving to fabric8 API
Works with EnvVar operator and can show reconfiguration of node.js threshold being automatically updated.
> Deploys multiple DeploymentConfigs with one 'app' per DC.

- manager/src/main/webapp/WEB-INF/web.xml
- manager/src/main/webapp/index.html
Added index.html back, which redirects to index.jsp
> Welcome page fixes

- README.md
- manager/src/main/java/io/streamzi/openshift/API.java
- manager/src/main/webapp/blocks/blocks.css
- manager/src/main/webapp/js/ui.js
- model/src/main/java/io/streamzi/openshift/dataflow/model/ProcessorConstants.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/ProcessorInputPort.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/ProcessorNode.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/serialization/SerializedNode.java
- watcher/src/main/java/io/streamzi/openshift/DeploymentConfigBuilder.java
Updated the code to allow the editor to list topics and attach them directly to the inputs of processor nodes.
> Direct topic attachment

- manager/src/main/java/io/streamzi/openshift/API.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/serialization/ProcessorTemplateYAMLReader.java
- model/src/test/java/io/streamzi/openshift/dataflow/tests/FunctioningFlowTest.java
- model/src/test/resources/logger.yaml
- model/src/test/resources/random-data.yaml
- watcher/src/main/java/io/streamzi/openshift/DeploymentConfigBuilder.java
> Slight changes to YamlReader, and removing dependency on operation filez

- README.md
- manager/pom.xml
> Wildfly Swarm -> Thorntail

- manager/pom.xml
- manager/src/main/java/io/streamzi/openshift/API.java
- manager/src/main/webapp/editor.jsp
- manager/src/main/webapp/index.jsp
- manager/src/main/webapp/js/ui.js
Round trip for flows. Doesn't preserve layout yet
> Reload flows

- manager/src/main/java/io/streamzi/openshift/API.java
Implemented API methods for getting flows from Custom Resources. Requires #40 for round tripping of flows.
> API for Flow Custom Resources

- manager/Dockerfile
> Docker image based on WF 14

- manager/src/main/webapp/editor.jsp
- manager/src/main/webapp/js/ui.js
Fixed round-tripping of the flows as hadn't been updated to use Custom Resource
> Rountripping flows

- manager/src/main/webapp/js/ui.js
- manager/startdebug.sh
- model/src/main/java/io/streamzi/openshift/dataflow/model/ProcessorNode.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/crds/ProcessorSpec.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/serialization/SerializedNode.java
Round trips data for multiple cloud replicas with the editor
> Multiple clouds with crds

- container/src/main/java/io/streamzi/openshift/dataflow/container/kafka/KafkaCloudEventOutputImpl.java
- model/src/main/java/io/streamzi/openshift/dataflow/deployment/FlowDeployment.java
- model/src/main/java/io/streamzi/openshift/dataflow/deployment/FlowDeploymentListBuilder.java
- model/src/main/java/io/streamzi/openshift/dataflow/deployment/LinkDeployment.java
- model/src/main/java/io/streamzi/openshift/dataflow/deployment/NodeDeployment.java
- model/src/test/java/io/streamzi/openshift/dataflow/tests/DataflowTestSuite.java
- model/src/test/java/io/streamzi/openshift/dataflow/tests/DeploymentTest.java
- model/src/test/resources/deployment-cr.json
Created the model for splitting a flow over multiple deployments.
> Adding model and partitioner for remote deployments

- container/pom.xml
- container/src/main/java/io/streamzi/openshift/dataflow/container/CloudEventInput.java
- container/src/main/java/io/streamzi/openshift/dataflow/container/kafka/KafkaCloudEventInputImpl.java
- container/src/main/java/io/streamzi/openshift/dataflow/container/kafka/KafkaCloudEventOutputImpl.java
- container/src/test/java/io/streamzi/openshift/dataflow/container/tests/ContainerTestSuite.java
- container/src/test/java/io/streamzi/openshift/dataflow/container/tests/MethodTest.java
- container/src/test/java/io/streamzi/openshift/dataflow/container/tests/POJOTest.java
- model/src/main/java/io/streamzi/openshift/dataflow/annotations/CloudEventConsumer.java
- model/src/main/java/io/streamzi/openshift/dataflow/annotations/CloudEventProducerTarget.java
- model/src/main/java/io/streamzi/openshift/dataflow/annotations/ObjectType.java
Supports passing arbitrary POJOs between processors
> Added POJO support to event flows

- manager/src/main/webapp/js/ui.js
- model/src/main/java/io/streamzi/openshift/dataflow/deployment/TargetState.java
- model/src/main/java/io/streamzi/openshift/dataflow/model/ProcessorNode.java
- model/src/main/java/io/streamzi/openshift/dataflow/serialization/SerializedNode.java
- model/src/test/java/io/streamzi/openshift/dataflow/tests/DeploymentTest.java
- model/src/test/resources/sticky-cr.json
- watcher/src/main/java/io/streamzi/openshift/ClientCache.java
Allow the user to specify the cloud where the topic will be created. If not specified will default to where the most replicas are.
> Allow Sticky Kafka Topics

- model/src/main/java/io/streamzi/eventflow/deployment/TargetState.java
- model/src/main/java/io/streamzi/eventflow/model/ProcessorFlow.java
- model/src/main/java/io/streamzi/eventflow/serialization/SerializedFlow.java
- model/src/test/java/io/streamzi/eventflow/tests/ModelTest.java
- model/src/test/resources/deployment-cr.json
- model/src/test/resources/flow-cr.json
- model/src/test/resources/sticky-cr.json
- ui/src/main/java/io/streamzi/eventflow/API.java
- ui/src/main/webapp/js/ui.js
done for https://github.com/project-streamzi/eventflow/issues/73
> Removing globalSettings from API/Framework

- README.md
**DO NOT MERGE**
it's based on https://github.com/project-streamzi/eventflow/pull/72 - that needs to go in first ... 
...
> Readme love

- operator/src/main/java/io/streamzi/eventflow/ClientCache.java
Constructs the value from the name of a Strimzi CR
> Changed method of getting local BOOTSTRAP_SERVERS

- model/pom.xml
- pom.xml
- runtime/src/main/java/io/streamzi/eventflow/runtime/kafka/KafkaCloudEventInputImpl.java
- runtime/src/test/java/io/streamzi/eventflow/runtime/tests/MethodTest.java
- runtime/src/test/java/io/streamzi/eventflow/runtime/tests/POJOTest.java
using the official API, as its now released
> WIP - using CNCF API

- model/pom.xml
- pom.xml
Thanks to @scholzj we can now use the pure upstream bits!
> Upstream strimzi is now available on central :tada:

- pom.xml
got security alerts for Jackson
> Fixing security bugs

- README.md
Fixes https://github.com/rh-event-flow/eventflow/issues/95
> Fixing broken link in readme
